<?php require('fixed/header.phtml');?>

    <div class="row container" id="sp_container">
        <div class="container col s12 l12">
            <h6 class="center"><strong>Reply Below:</strong></h6>
        </div>
        <div class="container row" id="register-fields">
            <form name="name" method="post" enctype="multipart/form-data" action="<?php echo ($_SERVER['PHP_SELF']); ?>">

                <div class="input-field col s12">
                    <textarea id="area2" class="materialize-textarea" name="post_body" data-length="1500" required></textarea>
                    <label for="area2">Write your post here...</label>
                </div><br>

                <!--Honeypot-->
                <div class="input-field col s12 hide">
                    <textarea id="area3" class="materialize-textarea" name="post_important" data-length="1500" hidden></textarea>
                </div><br>


                <?php
                if (isset($_POST['submit']))
                {
                    switch ($view->error) {
                        case $view->error = "err_file_type":
                            echo "<div class='left red-text container s12 l12' id='error_message2'>
                                  <p><strong>File is not an image</strong></p></div>";
                            break;
                    }
                }
                ?>

                <div class="container right" id="btn-under-alert">
                    <input class="btn-large black right z-depth-2" type="submit"
                           name="submit" value="Post">
                </div>
            </form>
        </div>
    </div>

<?php require('fixed/footer.phtml') ?>